on:
  workflow_dispatch:

name: CI

jobs:
  update_calendar:
    name: Update google calendar
    runs-on: ubuntu-latest
    env:
      METRO_LOGIN: ${{ secrets.METRO_LOGIN }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: run
